-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local primary_paletteKeyColor = "3a7f9f"

local secondary_paletteKeyColor = "667a86"

local tertiary_paletteKeyColor = "787397"

local neutral_paletteKeyColor = "73787c"

local neutral_variant_paletteKeyColor = "71787d"

local background = "f6fafe"

local onBackground = "171c1f"

local surface = "f6fafe"

local surfaceDim = "d6dade"

local surfaceBright = "f6fafe"

local surfaceContainerLowest = "ffffff"

local surfaceContainerLow = "f0f4f8"

local surfaceContainer = "eaeef2"

local surfaceContainerHigh = "e5e9ed"

local surfaceContainerHighest = "dfe3e7"

local onSurface = "171c1f"

local surfaceVariant = "dce3e9"

local onSurfaceVariant = "40484c"

local inverseSurface = "2c3134"

local inverseOnSurface = "edf1f5"

local outline = "6e767b"

local outlineVariant = "c0c7cd"

local shadow = "000000"

local scrim = "000000"

local surfaceTint = "186584"

local primary = "186584"

local onPrimary = "ffffff"

local primaryContainer = "c1e8ff"

local onPrimaryContainer = "004d67"

local inversePrimary = "8dcff2"

local secondary = "4d616c"

local onSecondary = "ffffff"

local secondaryContainer = "cee3f0"

local onSecondaryContainer = "364954"

local tertiary = "757094"

local onTertiary = "ffffff"

local tertiaryContainer = "757094"

local onTertiaryContainer = "ffffff"

local error = "ba1a1a"

local onError = "ffffff"

local errorContainer = "ffdad6"

local onErrorContainer = "93000a"

local primaryFixed = "c1e8ff"

local primaryFixedDim = "8dcff2"

local onPrimaryFixed = "001e2b"

local onPrimaryFixedVariant = "004d67"

local secondaryFixed = "d1e6f3"

local secondaryFixedDim = "b5c9d7"

local onSecondaryFixed = "091e27"

local onSecondaryFixedVariant = "364954"

local tertiaryFixed = "e5deff"

local tertiaryFixedDim = "c8c2ea"

local onTertiaryFixed = "1b1736"

local onTertiaryFixedVariant = "474364"

local term0 = "9a9b9b"

local term1 = "005bcc"

local term2 = "008d9f"

local term3 = "7e61b0"

local term4 = "009993"

local term5 = "006db8"

local term6 = "2b8aaa"

local term7 = "202225"

local term8 = "0f0f0f"

local term9 = "0071fa"

local term10 = "00b0c7"

local term11 = "9a7cce"

local term12 = "3fbdb6"

local term13 = "0088e3"

local term14 = "54abcc"

local term15 = "26282b"

local rosewater = "7d76b1"

local flamingo = "6470bd"

local pink = "0081d7"

local mauve = "005989"

local red = "003ee0"

local maroon = "2751f9"

local peach = "8a4dff"

local yellow = "008f68"

local green = "007a8c"

local teal = "00718f"

local sky = "0083af"

local sapphire = "007c9f"

local blue = "005f89"

local lavender = "0079ae"

local klink = "2390c0"

local klinkSelection = "2190bf"

local kvisited = "0386d3"

local kvisitedSelection = "0086d3"

local knegative = "607eff"

local knegativeSelection = "607eff"

local kneutral = "c794ff"

local kneutralSelection = "c794ff"

local kpositive = "00b9d8"

local kpositiveSelection = "00b9d7"

local text = "171c1f"

local subtext1 = "40484c"

local subtext0 = "6e767b"

local overlay2 = "7e868b"

local overlay1 = "91989d"

local overlay0 = "a3a9ae"

local surface2 = "b5bbc0"

local surface1 = "c9cfd3"

local surface0 = "e0e4e8"

local base = "f6fafe"

local mantle = "edf2f6"

local crust = "e7ecf1"

local success = "4F6354"

local onSuccess = "FFFFFF"

local successContainer = "D1E8D5"

local onSuccessContainer = "0C1F13"
