# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄
exec-once = wl-clipboard-history -t
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=/usr/lib/polkit-kde-authentication-agent-1

exec-once = hyprpaper
exec-once = hypridle

# set to primary for game compat
# gonna need to update this one once i know the name of the TV
#exec-once = xrandr --output DP-1 --primary

# unsure about this? commenting out for now
#exec-once = "/home/ntsu/scripts/wallpaper_rotate.sh --force"


# TODO: shell script launch-or-focus which checks if thing is launched and if it is then moves to that
# why am i writing that todo in here even?
# how would it even work with monocle?
# apparently using focuswindow dispatcher matched to window class will work

# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄2
# launching it like this puts it automatically in fullscreen but i want it non-fullscreen to make it work better with monocle idk
exec-once = [workspace 1 silent] "steam -tenfoot"
# other launchers, controller support might suck here
exec-once = [workspace 1 silent] heroic
exec-once = [workspace 1 silent] lutris
exec-once = [workspace 1 silent] rpcs3
exec-once = [workspace 1 silent] retroarch

# note to self maybe set up PWAs for jellyfin/youtube/whatever
