# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄
exec-once = wl-clipboard-history -t
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once = dunst
exec-once = swayosd-server

exec-once = hyprpaper
exec-once = hypridle

exec-once = antimicrox --hidden --profile ~/.config/antimicrox/generic.gamecontroller.amgp
# this is kind of brittle and might also not be needed since TVs generally only have 1 monitor
exec-once = xrandr --output $(hyprctl monitors -j | jq -r '.[0] | .name') --primary

# unsure about this? commenting out for now
#exec-once = "/home/ntsu/scripts/wallpaper_rotate.sh --force"


# TODO: shell script launch-or-focus which checks if thing is launched and if it is then moves to that
# why am i writing that todo in here even?
# how would it even work with monocle?
# apparently using focuswindow dispatcher matched to window class will work

# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄2
# launching it like this puts it automatically in fullscreen but i want it non-fullscreen to make it work better with monocle idk
exec-once = [workspace 1 silent] "steam -tenfoot"
# other launchers, controller support might suck here
#exec-once = [workspace 1 silent] heroic
exec-once = [workspace 1 silent] lutris
exec-once = [workspace 1 silent] rpcs3
exec-once = [workspace 1 silent] retroarch
exec-once = [workspace 1 silent] flatpak run com.github.iwalton3.jellyfin-media-player --tv
# note to self maybe set up PWAs for jellyfin/youtube/whatever
