# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀

# try to set default
$TERMINAL = ghostty
$BROWSER = helium-browser

# ▄▀█ █░█ █▀▄ █ █▀█
# █▀█ █▄█ █▄▀ █ █▄█
binde=, XF86AudioRaiseVolume, exec, swayosd-client --output-volume 5
binde=, XF86AudioLowerVolume, exec, swayosd-client --output-volume -5
binde=, XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bind=, XF86AudioPlay, exec, swayosd-client --playerctl play-pause
bind=, XF86AudioPause, exec, swayosd-client --playerctl play-pause
bind=, XF86AudioNext, exec, swayosd-client --playerctl next
bind=, XF86AudioPrev, exec, swayosd-client --playerctl previous

bind = SUPER, up, exec, swayosd-client --output-volume 5
bind = SUPER, down, exec, swayosd-client --output-volume -5

# █▀ █▀▀ █▀█ █▀▀ █▀▀ █▄░█ █▀ █░█ █▀█ ▀█▀
# ▄█ █▄▄ █▀▄ ██▄ ██▄ █░▀█ ▄█ █▀█ █▄█ ░█░
bind = , PRINT, exec, grim -o ~/Pictures/screenshots/capture_$(date '+%Y-%m-%d_%H-%M-%S').png && notify-send "Screenshot saved to default folder"
#bind = SUPERSHIFT, S, exec, ~/.config/scripts/screenshot_custom

bindr = SUPER, R, exec, killall rofi || rofi -show drun -theme ~/.config/rofi/global/custom.rasi
bindr = SUPER, W, exec, pkill -USR1 waybar

# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▄▀█ █▀▀ █▄░█ ▀█▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █░▀░█ █▀█ █░▀█ █▀█ █▄█ █░▀░█ ██▄ █░▀█ ░█░
bind = SUPER, Q, killactive,

# fullscreen/floating stuff
bind = SUPER, F, fullscreen,
#bind = SUPER, F, togglefloating,

# monocle
bind = SUPERSHIFT, right, layoutmsg, cyclenext
bind = SUPERSHIFT, left, layoutmsg, cycleprev

# below stuff is not relevant for tv system, however im leaving some way to return to workspace 1 in case something fucked up happens

# █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
# ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄
#bind = SUPER, c, togglespecialworkspace
#bind = SUPERSHIFT, c, movetoworkspace, special

# █▀ █░█░█ █ ▀█▀ █▀▀ █░█
# ▄█ ▀▄▀▄▀ █ ░█░ █▄▄ █▀█
bind = SUPER, 1, workspace, 1
#bind = SUPER, 2, workspace, 2
#bind = SUPER, 3, workspace, 3
#bind = SUPER, 4, workspace, 4
#bind = SUPER, 5, workspace, 5
#bind = SUPER, 6, workspace, 6
#bind = SUPER, 7, workspace, 7
#bind = SUPER, 8, workspace, 8
#bind = SUPER, 9, workspace, 9
#bind = SUPER, 0, workspace, 10
#bind = SHIFT ALT, right, workspace, e+1
#bind = SHIFT ALT, left, workspace, e-1

# █▀▄▀█ █▀█ █░█ █▀▀
# █░▀░█ █▄█ ▀▄▀ ██▄
bind = SUPER SHIFT, 1, movetoworkspace, 1
#bind = SUPER SHIFT, 2, movetoworkspace, 2
#bind = SUPER SHIFT, 3, movetoworkspace, 3
#bind = SUPER SHIFT, 4, movetoworkspace, 4
#bind = SUPER SHIFT, 5, movetoworkspace, 5
#bind = SUPER SHIFT, 6, movetoworkspace, 6
#bind = SUPER SHIFT, 7, movetoworkspace, 7
#bind = SUPER SHIFT, 8, movetoworkspace, 8
#bind = SUPER SHIFT, 9, movetoworkspace, 9
#bind = SUPER SHIFT, 0, movetoworkspace, 10

# █▀▄▀█ █▀█ █░█ █▀ █▀▀   █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀
# █░▀░█ █▄█ █▄█ ▄█ ██▄   █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█
#bindm = SUPER, mouse:272, movewindow
#bindm = SUPER, mouse:273, resizewindow
#bind = SUPER, mouse_down, workspace, e+1
#bind = SUPER, mouse_up, workspace, e-1
