# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# NVIDIA ENV VARS PLS NO DELET
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# force wayland in electron
env = ELECTRON_OZONE_PLATFORM_HINT,auto

#maybe dangerous, theoretically forces all wayland windows to use text input v3
env = WAYLAND_TEXT_INPUT=3

