# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█
windowrule {
  name = File-Progress_Float
  float = on
  match:class = file_progress
}

windowrule {
  name = Confirm-Dialog_Float
  float = on
  match:class = confirm
}

windowrule {
  name = Dialog_Float
  float = on
  match:class = dialog
}

windowrule {
  name = Download_Float
  float = on
  match:class = download
}

windowrule {
  name = Notification_Float_Top_Right
  float = on
  size = 64 256
  move = ((monitor_w*0.9)) (15)
  match:class = ^(notification)$
}

windowrule {
  name = Error_Float
  float = on
  match:class = error
}

windowrule {
  name = Splash_Float
  float = on
  match:class = splash
}

windowrule {
  name = Confirm-Reset_Float
  float = on
  match:class = confirmreset
}

windowrule {
  name = Open-File_Float
  float = on
  match:title = Open File
}

windowrule {
  name = Branch-Dialog_Float
  float = on
  match:title = branchdialog
}

windowrule {
  name = LXAppearance_Float
  float = on
  match:class = Lxappearance
}

windowrule {
  name = Rofi_Centered_No_Anim
  float = on
  animation = none
  center = on
  match:class = Rofi
}

windowrule {
  name = File-Roller_Float
  float = on
  match:class = file-roller
}

windowrule {
  name = Picture-in-Picture_Float
  float = on
  match:title = ^(Picture-in-Picture)$
}

windowrule {
  name = Steam_Chat_Float_Centered
  float = on
  match:class = steam
  match:title = negative:Steam
}

windowrule {
  name = Steam_Friends-List_Float
  float = on
  size = 400 600
  move = (monitor_w*0.84) (monitor_h*0.02)
  match:class = steam
  match:title = Friends List
}
