-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▀▀ ▀▄▀ █▀▀ █▀▀

-- ██▄ █░█ ██▄ █▄▄











-- set to primary for game compat


--waybar startup block, order matters here





-- fake cloud mount, disabling because it didnt work as expected

-- exec-once = /home/ntsu/scripts/heynote_fuse.sh

-- █▀▀ ▀▄▀ █▀▀ █▀▀

-- ██▄ █░█ ██▄ █▄▄2










-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("wl-clipboard-history -t")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("dunst")
    hl.exec_cmd("mega-cmd-server")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("xrandr --output DP-1 --primary")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("/home/ntsu/scripts/wbstartup.sh")
    hl.exec_cmd("sleep 0.1")
    hl.exec_cmd("/home/ntsu/scripts/wallpaper_rotate.sh --force")
    hl.exec_cmd("[workspace 1 silent; monitor HDMI-A-1] ghostty")
    hl.exec_cmd("hyprctl dispatch workspace 2")
    hl.exec_cmd("[workspace 2 silent; monitor DP-1] helium-browser")
    hl.exec_cmd("[workspace 2 silent; monitor DP-1] vesktop")
    hl.exec_cmd("hyprctl dispatch workspace 3")
    hl.exec_cmd("[workspace 3 silent; float; move (monitor_w*0.84) (monitor_h*0.8); size 400 600; monitor DP-1] easyeffects")
    hl.exec_cmd("[workspace 3 silent; float; move (monitor_w*0.84) (monitor_h*0.02); size 300 564; monitor DP-1]/opt/piavpn/bin/pia-client --clear-cache")
    hl.exec_cmd("[workspace 3 silent; float; move (monitor_w*0) (monitor_h*0.8); size 600 800; monitor DP-1]/home/ntsu/signal-desktop.AppImage")
    hl.exec_cmd("hyprctl dispatch workspace 2")
end)
