-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄
-- █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀

-- try to set default

local TERMINAL = "ghostty"

local BROWSER = "helium-browser"

-- temp waybar toggle

hl.bind("SUPER + F1", hl.dsp.exec_cmd("pkill -USR1 waybar"))

-- ▄▀█ █░█ █▀▄ █ █▀█
-- █▀█ █▄█ █▄▀ █ █▄█

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- █▀ █▀▀ █▀█ █▀▀ █▀▀ █▄░█ █▀ █░█ █▀█ ▀█▀
-- ▄█ █▄▄ █▀▄ ██▄ ██▄ █░▀█ ▄█ █▀█ █▄█ ░█░

hl.bind("PRINT", hl.dsp.exec_cmd("grim - | wl-copy"))

hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("~/.config/scripts/screenshot_custom"))

-- █▀▄▀█ █ █▀ █▀▀
-- █░▀░█ █ ▄█ █▄▄

hl.bind("SUPER + SHIFT + X", hl.dsp.exec_cmd("hyprpicker -a"))

hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock"))

hl.bind("SUPER + T", hl.dsp.exec_cmd("ghostty"))

hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("[float; center; size 1024 1024] ghostty -e zsh"))

hl.bind("SUPER + E", hl.dsp.exec_cmd("thunar"))

hl.bind("SUPER + W", hl.dsp.exec_cmd("helium-browser"))

hl.bind("SUPER + M", hl.dsp.exec_cmd("code"))

hl.bind("SUPER + Space", hl.dsp.exec_cmd("killall rofi || rofi -show drun -theme ~/.config/rofi/global/custom.rasi"), { release = true })

hl.bind("SUPER + J", hl.dsp.exec_cmd("fcitx5-remote -t &&/home/ntsu/.config/waybar/scripts/sendsignal.sh top SIGRTMIN 5"))

-- Test global copy/paste

hl.bind("SUPER + C", hl.dsp.exec_cmd("~/scripts/smartcopypaste.sh copy ghostty"))

hl.bind("SUPER + V", hl.dsp.exec_cmd("~/scripts/smartcopypaste.sh paste ghostty"))

hl.bind("SUPER + X", hl.dsp.exec_cmd("~/scripts/smartcopypaste.sh cut ghostty"))

-- █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▄▀█ █▀▀ █▄░█ ▀█▀
-- ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █░▀░█ █▀█ █░▀█ █▀█ █▄█ █░▀░█ ██▄ █░▀█ ░█░

hl.bind("SUPER + Q", hl.dsp.window.close())

-- im dum and sometimes accidentally kill my entire session so temp disable

-- bind = SUPER SHIFT, Q, exit,

-- dwindle

hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen())

hl.bind("SUPER + F", hl.dsp.window.float())

hl.bind("SUPER + P", hl.dsp.window.pseudo())

--bind = SUPER, S, togglesplit,

-- monocle

hl.bind("SUPER + TAB", hl.dsp.layout("cyclenext"))

-- █▀▀ █▀█ █▀▀ █░█ █▀
-- █▀░ █▄█ █▄▄ █▄█ ▄█

hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))

hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))

--Vim bindings

--bind = SUPER, H, movefocus, l

--bind = SUPER, L, movefocus, r

--bind = SUPER, K, movefocus, u

-- if you ever become a vimmer, dont forget that this is your JP shortcut as well

--bind = SUPER, J, movefocus, d

-- █▀▄▀█ █▀█ █░█ █▀▀

-- █░▀░█ █▄█ ▀▄▀ ██▄

hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "left" }))

hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "right" }))

hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "up" }))

hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "down" }))

--Vim bindings

hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "left" }))

hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "right" }))

hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "up" }))

hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "down" }))

-- █▀█ █▀▀ █▀ █ ▀█ █▀▀

-- █▀▄ ██▄ ▄█ █ █▄ ██▄

hl.bind("SUPER + CTRL + left", hl.dsp.window.resize({ x = -20, y = 0, relative = true }))

hl.bind("SUPER + CTRL + right", hl.dsp.window.resize({ x = 20, y = 0, relative = true }))

hl.bind("SUPER + CTRL + up", hl.dsp.window.resize({ x = 0, y = -20, relative = true }))

hl.bind("SUPER + CTRL + down", hl.dsp.window.resize({ x = 0, y = 20, relative = true }))

-- ▀█▀ ▄▀█ █▄▄ █▄▄ █▀▀ █▀▄

-- ░█░ █▀█ █▄█ █▄█ ██▄ █▄▀

-- tbh I dont use this so imma just uncomment it

--bind= SUPER, g, togglegroup

--bind= SUPER, tab, changegroupactive

-- █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░

-- ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

--bind = SUPER, c, togglespecialworkspace

--bind = SUPERSHIFT, c, movetoworkspace, special

-- █▀ █░█░█ █ ▀█▀ █▀▀ █░█

-- ▄█ ▀▄▀▄▀ █ ░█░ █▄▄ █▀█

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))

hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))

hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))

hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))

hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))

hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))

hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))

hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))

hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))

hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind("SHIFT + ALT + right", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SHIFT + ALT + left", hl.dsp.focus({ workspace = "e-1" }))

-- █▀▄▀█ █▀█ █░█ █▀▀

-- █░▀░█ █▄█ ▀▄▀ ██▄

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))

hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))

hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))

hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))

hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))

hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))

hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))

hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))

hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))

hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- █▀▄▀█ █▀█ █░█ █▀ █▀▀   █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀

-- █░▀░█ █▄█ █▄█ ▄█ ██▄   █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
