-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▀▀ █░█ █▀█ █▀ █▀█ █▀█

-- █▄▄ █▄█ █▀▄ ▄█ █▄█ █▀▄

hl.config({
    cursor = {
        no_hardware_cursors = 1,
        inactive_timeout = 60,
    },
})
