-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█

-- █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█

hl.config({
    decoration = {
        -- █▀█ █▀█ █░█ █▄░█ █▀▄   █▀▀ █▀█ █▀█ █▄░█ █▀▀ █▀█
        -- █▀▄ █▄█ █▄█ █░▀█ █▄▀   █▄▄ █▄█ █▀▄ █░▀█ ██▄ █▀▄
        rounding = 6,
        rounding_power = 2.0,
        -- █▀█ █▀█ ▄▀█ █▀▀ █ ▀█▀ █▄█
        -- █▄█ █▀▀ █▀█ █▄▄ █ ░█░ ░█░
        active_opacity = 1.0,
        inactive_opacity = 0.8,
        -- █▄▄ █░░ █░█ █▀█
        -- █▄█ █▄▄ █▄█ █▀▄
        blur = {
            enabled = true,
            size = 3,
            passes = 3,
            new_optimizations = true,
        },
        -- █▀ █░█ ▄▀█ █▀▄ █▀█ █░█░█
        -- ▄█ █▀█ █▀█ █▄▀ █▄█ ▀▄▀▄▀
        shadow = {
            enabled = true,
            range = 10,
            render_power = 2,
            --ignore_window = true
            color = "0x66000000",
        },
    },
})
