-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
-- █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█

hl.config({
    decoration = {
        -- █▄▄ █░░ █░█ █▀█
        -- █▄█ █▄▄ █▄█ █▀▄
        blur = {
            enabled = true,
            size = 2,
            passes = 2,
            new_optimizations = true,
            variant = glass
        },
    },
})
