-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀

-- █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

hl.config({
    dwindle = {
        --  pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
    },
})
