-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▀▀ █▀▀ █▄░█ █▀▀ █▀█ ▄▀█ █░░

-- █▄█ ██▄ █░▀█ ██▄ █▀▄ █▀█ █▄▄

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 0,
        --  no_border_on_floating = false
        layout = "dwindle",
        resize_on_border = true,
        -- lets see if this is ok
        col = {
            active_border = "0xffFFFFFF",
            inactive_border = "0xffacacac",
        },
    },
})
