-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █ █▄░█ █▀█ █░█ ▀█▀

-- █ █░▀█ █▀▀ █▄█ ░█░

hl.config({
    input = {
        kb_layout = "se",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
    },
})
