-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.layer_rule({
    match = {
        namespace = "gtk-layer-shell",
    },
    blur = true,
})

--layerrule = blur, waybar

hl.layer_rule({
    match = {
        namespace = "lockscreen",
    },
    blur = true,
})
