-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█

-- █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

hl.monitor(
    {
        output = "HDMI-A-1",
        mode = "1920x1080@100.00Hz",
        position = "0x0",
        scale = 1,
        transform = 0,
    })
-- NOTE: Section 'monitorv2' may be a plugin or custom section; verify the output

hl.monitor(
    {
        output = "DP-1",
        mode = "2560x1440@120",
        position = "1920x0",
        scale = 1,
    })
-- NOTE: Section 'monitorv2' may be a plugin or custom section; verify the output


-- Set up workspaces

hl.workspace_rule({
    workspace = 1,
    monitor = "HDMI-A-1",
    default = true,
    persistent = true,
    default_name = "monoclevert",
    layout = "monocle",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-1",
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("sleep 2")
end)
