-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
-- ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

hl.window_rule({
    name  = "File-Progress_Float",
    match = {
        class = "file_progress",
    },
    float = true,
})

hl.window_rule({
    name  = "Confirm-Dialog_Float",
    match = {
        class = "confirm",
    },
    float = true,
})

hl.window_rule({
    name  = "Dialog_Float",
    match = {
        class = "dialog",
    },
    float = true,
})

hl.window_rule({
    name  = "Download_Float",
    match = {
        class = "download",
    },
    float = true,
})

hl.window_rule({
    name  = "Notification_Float_Top_Right",
    match = {
        class = "^(notification)$",
    },
    float = true,
    size = { 64, 256 },
    move = { "((monitor_w*0.9))", "(15)" },
})

hl.window_rule({
    name  = "Error_Float",
    match = {
        class = "error",
    },
    float = true,
})

hl.window_rule({
    name  = "Splash_Float",
    match = {
        class = "splash",
    },
    float = true,
})

hl.window_rule({
    name  = "Confirm-Reset_Float",
    match = {
        class = "confirmreset",
    },
    float = true,
})

hl.window_rule({
    name  = "Open-File_Float",
    match = {
        title = "Open File",
    },
    float = true,
})

hl.window_rule({
    name  = "Branch-Dialog_Float",
    match = {
        title = "branchdialog",
    },
    float = true,
})

hl.window_rule({
    name  = "LXAppearance_Float",
    match = {
        class = "Lxappearance",
    },
    float = true,
})

hl.window_rule({
    name  = "Rofi_Centered_No_Anim",
    match = {
        class = "Rofi",
    },
    float = true,
    animation = "none",
    center = true,
})

hl.window_rule({
    name  = "Viewnior_Float",
    match = {
        class = "^(viewnior)$",
    },
    float = true,
})

hl.window_rule({
    name  = "Feh_Float",
    match = {
        class = "feh",
    },
    float = true,
})

hl.window_rule({
    name  = "PulseAudio-Qt_Float",
    match = {
        class = "pavucontrol-qt",
    },
    float = true,
})

hl.window_rule({
    name  = "PulseAudio_Float",
    match = {
        class = "pavucontrol",
    },
    float = true,
})

hl.window_rule({
    name  = "File-Roller_Float",
    match = {
        class = "file-roller",
    },
    float = true,
})

hl.window_rule({
    name  = "Wlogout_Fullscreen",
    match = {
        class = "wlogout",
    },
    fullscreen = true,
})

hl.window_rule({
    name  = "Wlogout_Float_Fullscreen",
    match = {
        title = "wlogout",
    },
    float = true,
    fullscreen = true,
})

hl.window_rule({
    name  = "MPV_Idle_Inhibit_Focus",
    match = {
        class = "mpv",
    },
    idle_inhibit = "focus",
})

hl.window_rule({
    name  = "Firefox_Idle_Inhibit_Fullscreen",
    match = {
        class = "firefox",
    },
    idle_inhibit = "fullscreen",
})

hl.window_rule({
    name  = "Media-Viewer_Float",
    match = {
        title = "^(Media viewer)$",
    },
    float = true,
})

hl.window_rule({
    name  = "Volume-Control_Float_Size_Pos",
    match = {
        title = "^(Volume Control)$",
    },
    float = true,
    size = { 800, 600 },
    move = { "(15)", "((monitor_h*0.04))" },
})

hl.window_rule({
    name  = "Picture-in-Picture_Float",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
})

hl.window_rule({
    name  = "YouTube_Opaque_Active",
    match = {
        title = "^(.*)(- YouTube)(.*)$",
    },
    opacity = "1.0 override 1.0 override",
})

hl.window_rule({
    name  = "Ghostty_Terminal_Opacity_Override",
    match = {
        class = "^(.*)(ghostty)(.*)$",
    },
    opacity = "0.8 override 0.5 override",
})

hl.window_rule({
    name  = "Ghostty_No-Blur_Workspace-1",
    match = {
        class = "^(.*)(ghostty)(.*)$",
        workspace = 1,
        focus = 0,
    },
    no_blur = true,
})

hl.window_rule({
    name  = "Borderless_Float",
    match = {
        float = true,
    },
    border_size = 0,
})

hl.window_rule({
    name  = "Steam_Chat_Float_Centered",
    match = {
        class = "steam",
        title = "negative:Steam",
    },
    float = true,
})

hl.window_rule({
    name  = "Steam_Friends-List_Float",
    match = {
        class = "steam",
        title = "Friends List",
    },
    float = true,
    size = { 400, 600 },
    move = { "(monitor_w*0.84)", "(monitor_h*0.02)" },
})

hl.window_rule({
    name  = "Lower_Opacity_Workspace_3",
    match = {
        workspace = 3,
    },
    opacity = "1.0 override 0.3 override 0.5 override",
    no_blur = true,
})

hl.window_rule({
    name  = "Float_and_center_satty",
    match = {
        class = "^(.*)(satty)(.*)$",
        title = "satty",
    },
    float = true,
    center = true,
    no_blur = true,
})
