cursor #fff2ec
cursor_text_color #d6c3b7

foreground            #fff2ec
background            #19120d
selection_foreground  #311c0d
selection_background  #e4bfa7
url_color             #ffb783

color0   #19120d
color1   #ff7972
color2   #95ff7f
color3   #ffe672
color4   #f2a064
color5   #76380c
color6   #ffb783
color7   #fff6ef
color8   #46413e
color9   #ffa49f
color10  #b5ffa5
color11  #ffefa5
color12  #ffc195
color13  #ffcca8
color14  #ffdec7
color15  #fffbf8
