cursor #f8f3fb
cursor_text_color #cac4cf

foreground            #f8f3fb
background            #141318
selection_foreground  #231e31
selection_background  #cbc3dc
url_color             #cebdff

color0   #141318
color1   #ff7290
color2   #7fff99
color3   #ffda72
color4   #baa7f2
color5   #7a6ba7
color6   #cebdff
color7   #f3efff
color8   #43414a
color9   #ff9fb3
color10  #a5ffb8
color11  #ffe7a5
color12  #d5c6ff
color13  #dcd0ff
color14  #e8e1ff
color15  #faf8ff
