$NERDFONT = Hack Nerd Font Mono
$NICEFONT = Gotham Bold

background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
}

# Power Menu block

# poweroff label
label {
    monitor = DP-1
    text = 
    onclick = poweroff
    color = rgba(200, 200, 200, 1.0)
    font_size = 128
    font_family = Hack Nerd Font Mono

    position = -25%, 0
}

# poweroff text
label {
    monitor = DP-1
    text = Shut Down
    color = rgba(200, 200, 200, 1.0)
    font_size = 24
    font_family = Gotham Bold

    position = -25%, -10%
}

# reboot label
label {
    monitor = DP-1
    text = 
    onclick = reboot
    color = rgba(200, 200, 200, 1.0)
    font_size = 128
    font_family = Hack Nerd Font Mono

    position = -8.33%, 0
}

# reboot text
label {
    monitor = DP-1
    text = Reboot
    color = rgba(200, 200, 200, 1.0)
    font_size = 24
    font_family = Gotham Bold

    position = -8.33%, -10%
}

# suspend/sleep label
label {
    monitor = DP-1
    text = 󰤄
    onclick = systemctl suspend
    color = rgba(200, 200, 200, 1.0)
    font_size = 128
    font_family = Hack Nerd Font Mono

    position = 8.33%, 0
}

# suspend/sleep text
label {
    monitor = DP-1
    text = Sleep
    color = rgba(200, 200, 200, 1.0)
    font_size = 24
    font_family = Gotham Bold

    position = 8.33%, -10%
}

# return label
label {
    monitor = DP-1
    text = 󰌑
    onclick = pkill -USR1 hyprlock
    color = rgba(200, 200, 200, 1.0)
    font_size = 128
    font_family = Hack Nerd Font Mono

    position = 25%, 0
}

# return text
label {
    monitor = DP-1
    text = Return
    color = rgba(200, 200, 200, 1.0)
    font_size = 24
    font_family = Gotham Bold

    position = 25%, -10%
}
