-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "DP-1", mode = "2560x1440@119.879", position = "1920x0", scale = 1, vrr = 0 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.000", position = "0x360", scale = 1, vrr = 0 })
