[background]
path = "/usr/share/wallpapers/syokonowatermark.jpg"
fit = "Fill"

[env]
#no custom env vars needed yet

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Nordic"

# Font name and size
font_name = "Monofur Nerd Font 16"

# Icon theme name
icon_theme_name = "Adwaita"

# GTK theme name
theme_name = "Nordic"

[appearance]
# Override welcome message
greeting_msg = ""

[commands]
# The command used to reboot the system
reboot = [ "systemctl", "reboot" ]

# The command used to shut down the system
poweroff = [ "systemctl", "poweroff" ]
